version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
    groups:
      runtime-dependencies:
        patterns:
          - "org.jetbrains.kotlin:kotlin-gradle-plugin:*"
          - "org.jetbrains.dokka:dokka-gradle-plugin:*"
          - "io.github.gradle-nexus:publish-plugin:*"
          - "com.palantir.gradle.gitversion:gradle-git-version:*"
          - "org.springframework.boot:spring-boot-gradle-plugin:*"
          - "io.spring.gradle:dependency-management-plugin:*"
          - "org.jetbrains.kotlin:kotlin-allopen:*"
